name: Building Base Savings Account Service

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write
  repository-projects: read
  contents: read
  issues: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
